# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "912a83c9af84369d4d44b6f0bd6c8905"
name = "pros-app"
application_url = "https://cdn.enjob.ca"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# This was missing read_customers!
scopes = "write_products,read_customers"

[auth]
# We must list all valid OAuth callback URLs here
redirect_urls = [
  "https://cdn.enjob.ca/auth/callback",
  "https://cdn.enjob.ca/auth/shopify/callback",
  "https://cdn.enjob.ca/api/auth/callback"
]

# This connects your Storefront to your App
[app_proxy]
url = "https://cdn.enjob.ca/app/proxy"
subpath = "vip-status"
prefix = "apps"
